"""Tests for the single-layer-solenoid coil-property extractor.

The primary check is a regression against the QOIL semi-analytical reference
(References/hamwaves_inductance_calculator/inductance.py): the ported pipeline must
reproduce QOIL's L_s, L_eff, R, Q, C_p and f_res to display precision. Reference values
were generated by running QOIL's own scalar math (its polynomial Bessel approximations
and SLATEC fzero) headless; the port here uses scipy.special / brentq and matches to
~6 significant figures. Also cross-checks the current-sheet inductance against the
field-based Biot-Savart / Neumann inductance and asserts the expected physical trends.
"""

from __future__ import annotations

import sys
import unittest
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from spin_dynamics.fields.coil_properties import (  # noqa: E402
    ANNEALED_COPPER,
    SILVER,
    CoilProperties,
    ConductorMaterial,
    medhurst_proximity_factor,
    sheath_helix_dispersion,
    solenoid_field_inductance,
    solenoid_properties,
)

# QOIL reference outputs, keyed by (kwargs). Generated from the vendored inductance.py
# math (see module docstring). Units: L in henry, R/X in ohm, C in farad, f in Hz.
_QOIL_REFERENCE = {
    "normal": {
        "kwargs": dict(diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6),
        "proximity_phi": 1.345948,
        "effective_diameter": 19.8620e-3,
        "ac_resistance": 0.144799,
        "inductance_currentsheet": 1.035194e-6,
        "inductance_effective": 1.059576e-6,
        "q_factor": 229.8873,
        "stray_capacitance": 22.523139e-12,
        "self_resonant_frequency": 179.892674e6,
    },
    "cubical_highq": {
        "kwargs": dict(diameter=30e-3, length=30e-3, turns=12, wire_diameter=2.0e-3, frequency=20e6),
        "proximity_phi": 3.170000,
        "effective_diameter": 29.1233e-3,
        "ac_resistance": 0.597062,
        "inductance_currentsheet": 2.658179e-6,
        "inductance_effective": 2.672951e-6,
        "q_factor": 562.5762,
        "stray_capacitance": 0.131659e-12,
        "self_resonant_frequency": 91.940152e6,
    },
    "long_thin": {
        "kwargs": dict(diameter=10e-3, length=100e-3, turns=40, wire_diameter=1.0e-3, frequency=10e6),
        "proximity_phi": 1.580000,
        "effective_diameter": 9.7956e-3,
        "ac_resistance": 0.510282,
        "inductance_currentsheet": 1.465177e-6,
        "inductance_effective": 1.578961e-6,
        "q_factor": 194.4200,
        "stray_capacitance": 12.458577e-12,
        "self_resonant_frequency": 139.790936e6,
    },
    "single_turn": {
        "kwargs": dict(diameter=15e-3, length=3e-3, turns=1, wire_diameter=2.0e-3, frequency=50e6),
        "proximity_phi": 2.071723,
        "effective_diameter": 14.3895e-3,
        "ac_resistance": 0.027687,
        "inductance_currentsheet": 0.020977e-6,
        "inductance_effective": 0.021554e-6,
        "q_factor": 244.5616,
        "stray_capacitance": 12.924797e-12,
        "self_resonant_frequency": 1687.366548e6,
    },
}


class QOILRegressionTests(unittest.TestCase):
    def test_matches_qoil_reference(self) -> None:
        for name, ref in _QOIL_REFERENCE.items():
            with self.subTest(design=name):
                r = solenoid_properties(**ref["kwargs"])
                for field, expected in ref.items():
                    if field == "kwargs":
                        continue
                    got = getattr(r, field)
                    self.assertTrue(np.isfinite(got), f"{name}.{field} is not finite")
                    # ~0.05% tolerance covers scipy-Bessel vs QOIL-polynomial differences.
                    self.assertLess(
                        abs(got - expected) / abs(expected),
                        5e-4,
                        f"{name}.{field}: got {got!r}, expected {expected!r}",
                    )

    def test_silver_lowers_resistance_vs_copper(self) -> None:
        kw = dict(diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6)
        r_cu = solenoid_properties(material=ANNEALED_COPPER, **kw).ac_resistance
        r_ag = solenoid_properties(material=SILVER, **kw).ac_resistance
        self.assertLess(r_ag, r_cu)  # silver is less resistive


class MedhurstTests(unittest.TestCase):
    def test_exact_at_table_nodes(self) -> None:
        # Interior grid nodes must return the tabulated value exactly (bilinear interp).
        # l/D = 0.6 (row 3), p/d = 1.667 (col 4) -> 1.89 in the Medhurst table.
        self.assertAlmostEqual(medhurst_proximity_factor(0.6, 1.667), 1.89, places=6)
        # l/D = 2 (row 6), p/d = 2 (col 5) -> 1.74.
        self.assertAlmostEqual(medhurst_proximity_factor(2.0, 2.0), 1.74, places=6)

    def test_monotonic_decrease_with_spacing(self) -> None:
        # Wider spacing (larger p/d) reduces the proximity factor toward 1.
        phi_close = medhurst_proximity_factor(1.0, 1.111)
        phi_wide = medhurst_proximity_factor(1.0, 5.0)
        self.assertGreater(phi_close, phi_wide)
        self.assertGreaterEqual(phi_wide, 1.0)


class DispersionTests(unittest.TestCase):
    def test_beta_between_k0_and_bound_zc_positive(self) -> None:
        f = 20e6
        a = 0.015
        psi = np.arctan(0.0025 / (np.pi * 0.03))
        beta, tau, z_c = sheath_helix_dispersion(f, a, psi)
        k0 = 2 * np.pi * f / 299792458.0
        # Guided mode is slow: beta > k0, tau real & positive, Z_c positive.
        self.assertGreater(beta, k0)
        self.assertGreater(tau, 0.0)
        self.assertGreater(z_c, 0.0)


class FieldCrossCheckTests(unittest.TestCase):
    def test_currentsheet_matches_field_inductance(self) -> None:
        for kw in (
            dict(diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3),
            dict(diameter=10e-3, length=100e-3, turns=40, wire_diameter=1.0e-3),
            dict(diameter=30e-3, length=30e-3, turns=12, wire_diameter=2.0e-3),
        ):
            with self.subTest(**kw):
                l_field = solenoid_field_inductance(**kw)
                l_sheet = solenoid_properties(frequency=5e6, **kw).inductance_currentsheet
                # Two independent models (stacked-loop partial-L vs current-sheet formula)
                # should agree to ~15%.
                self.assertLess(abs(l_field - l_sheet) / l_sheet, 0.15)


class PhysicsTrendTests(unittest.TestCase):
    def test_thicker_wire_raises_q(self) -> None:
        base = dict(diameter=20e-3, length=30e-3, turns=10, frequency=5e6)
        q_thin = solenoid_properties(wire_diameter=0.5e-3, **base).q_factor
        q_thick = solenoid_properties(wire_diameter=2.0e-3, **base).q_factor
        self.assertGreater(q_thick, q_thin)

    def test_more_turns_lowers_self_resonance(self) -> None:
        base = dict(diameter=20e-3, length=40e-3, wire_diameter=1.0e-3, frequency=5e6)
        f_few = solenoid_properties(turns=8, **base).self_resonant_frequency
        f_many = solenoid_properties(turns=20, **base).self_resonant_frequency
        self.assertGreater(f_few, f_many)

    def test_ac_resistance_scales_as_sqrt_frequency(self) -> None:
        base = dict(diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3)
        r1 = solenoid_properties(frequency=5e6, **base).ac_resistance
        r4 = solenoid_properties(frequency=20e6, **base).ac_resistance
        # 4x frequency -> ~2x skin-limited resistance. The finite-skin-depth (-delta^2)
        # correction makes it grow marginally slower than exactly sqrt(f).
        self.assertGreater(r4 / r1, 1.9)
        self.assertLess(r4 / r1, 2.0)

    def test_self_resonance_above_design_and_stray_c_positive(self) -> None:
        r = solenoid_properties(
            diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6
        )
        self.assertGreater(r.self_resonant_frequency, r.frequency)
        self.assertGreater(r.stray_capacitance, 0.0)


class HelperTests(unittest.TestCase):
    def test_tuning_capacitance_resonates_inductance(self) -> None:
        r = solenoid_properties(
            diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6
        )
        c = r.tuning_capacitance()
        omega = 2 * np.pi * r.frequency
        self.assertAlmostEqual(omega**2 * r.inductance * c, 1.0, places=9)

    def test_to_probe_params_keys(self) -> None:
        r = solenoid_properties(
            diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6
        )
        sp = r.to_probe_params()
        self.assertEqual(set(sp), {"L", "R", "C"})
        self.assertAlmostEqual(sp["L"], r.inductance)
        self.assertAlmostEqual(sp["R"], r.ac_resistance)

    def test_validation_rejects_overlapping_turns(self) -> None:
        # Wire diameter exceeding the pitch would overlap turns.
        with self.assertRaises(ValueError):
            solenoid_properties(
                diameter=20e-3, length=5e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6
            )

    def test_returns_coil_properties_dataclass(self) -> None:
        r = solenoid_properties(
            diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6
        )
        self.assertIsInstance(r, CoilProperties)


class MaterialTemperatureTests(unittest.TestCase):
    _kw = dict(diameter=20e-3, length=30e-3, turns=10, wire_diameter=1.0e-3, frequency=5e6)

    def test_reference_resistivity_recovered(self) -> None:
        # No temperature (or the reference temperature) reproduces the tabulated value.
        self.assertEqual(ANNEALED_COPPER.resistivity_at(), ANNEALED_COPPER.resistivity)
        self.assertAlmostEqual(
            ANNEALED_COPPER.resistivity_at(ANNEALED_COPPER.reference_temperature),
            ANNEALED_COPPER.resistivity,
            places=18,
        )

    def test_default_temperature_matches_room_temperature(self) -> None:
        # The temperature argument must not change the default (room-temperature) result.
        r_default = solenoid_properties(**self._kw)
        r_room = solenoid_properties(temperature=293.15, **self._kw)
        self.assertAlmostEqual(r_default.ac_resistance, r_room.ac_resistance, places=12)
        self.assertEqual(r_default.temperature, 293.15)
        self.assertAlmostEqual(r_default.resistivity, ANNEALED_COPPER.resistivity, places=18)

    def test_hot_coil_raises_resistance_lowers_q(self) -> None:
        r_room = solenoid_properties(**self._kw)
        r_hot = solenoid_properties(temperature=350.0, **self._kw)
        self.assertGreater(r_hot.ac_resistance, r_room.ac_resistance)
        self.assertLess(r_hot.q_factor, r_room.q_factor)
        # Only R (via resistivity) is temperature-dependent; L is geometric.
        self.assertAlmostEqual(r_hot.inductance_effective, r_room.inductance_effective, places=12)

    def test_cryogenic_rrr_lowers_resistance_raises_q(self) -> None:
        ofhc = ConductorMaterial(
            "OFHC copper", 17.241e-9, 0.99999044,
            temp_coefficient=3.93e-3, residual_resistivity_ratio=100.0,
        )
        r_room = solenoid_properties(material=ofhc, temperature=293.15, **self._kw)
        r_cryo = solenoid_properties(material=ofhc, temperature=77.0, **self._kw)
        self.assertLess(r_cryo.ac_resistance, r_room.ac_resistance)
        self.assertGreater(r_cryo.q_factor, r_room.q_factor)

    def test_rrr_floor_at_low_temperature(self) -> None:
        # Well below the reference temperature the Matthiessen resistivity approaches the
        # residual floor rho_ref / RRR (from above), never below it.
        rrr = 200.0
        m = ConductorMaterial("copper", 17.241e-9, 1.0, temp_coefficient=3.93e-3,
                              residual_resistivity_ratio=rrr)
        floor = 17.241e-9 / rrr
        self.assertGreaterEqual(m.resistivity_at(1.0), floor)
        self.assertLess(m.resistivity_at(1.0), 0.05 * 17.241e-9)  # far below room value

    def test_negative_temperature_rejected(self) -> None:
        with self.assertRaises(ValueError):
            ANNEALED_COPPER.resistivity_at(-10.0)


if __name__ == "__main__":
    unittest.main()
