"""Bayesian experiment-design tools.

The generic core provides NumPy grid/particle inference, likelihood-
backed predictive models, finite candidate spaces, information and QoI-risk
utilities, physical costs, constraints, stopping, and replayable sessions.
Phase 2 binds representative experiments; Phase 3 adds prediction batching,
validated surrogates, staged scoring, nuisance marginalization, and robustness
reports. Phase 4 adds recoverable small-batch operation through an external
instrument protocol. Phase 0 remains available as an exact-grid
inversion-recovery reference.
"""

from spin_dynamics.design.adapters import (
    CPMGIRAdapter,
    CPMGIRDesign,
    ESRDelayDesign,
    ESRHahnAdapter,
    ExperimentAdapterCost,
    ExperimentDesignAdapter,
    ExperimentPlanConstraint,
    ExperimentPredictor,
    NQRFIDAdapter,
    NQRFrequencyDesign,
    NanoMRQdyneAdapter,
    NanoMRQdyneDesign,
    PGSEAdapter,
    PGSEDesign,
    make_adapter_model,
    make_adapter_session,
)
from spin_dynamics.design.adapter_benchmarks import (
    make_cpmg_ir_benchmark,
    make_esr_hahn_benchmark,
    make_nqr_fid_benchmark,
    make_pgse_benchmark,
    make_phase2_adapter_benchmarks,
)
from spin_dynamics.design.benchmarks import (
    AdapterBenchmarkProblem,
    AdapterBenchmarkResult,
    BenchmarkPolicySummary,
    BenchmarkTracePoint,
    BenchmarkTrial,
    CandidatePredictionTable,
    run_adapter_benchmark,
    save_benchmark_results,
)

from spin_dynamics.design.constraints import (
    CallableConstraint,
    ConstraintResult,
    DesignConstraint,
    evaluate_constraints,
)
from spin_dynamics.design.costs import CallableCost, ConstantCost
from spin_dynamics.design.diagnostics import (
    CredibleIntervalStopping,
    PosteriorStandardDeviationStopping,
    PosteriorSummary,
    QuantityOfInterest,
    quantity_values,
    summarize_quantity,
    weighted_mean,
    weighted_quantile,
    weighted_variance,
)
from spin_dynamics.design.io import (
    load_design_state,
    save_design_state,
    save_design_state_atomic,
    state_from_json,
    state_to_json,
)
from spin_dynamics.design.live import (
    AcquisitionOutcome,
    AcquisitionRequest,
    BatchExecution,
    DesignInstrument,
    LiveDesignSession,
    PendingBatch,
)
from spin_dynamics.design.likelihoods import (
    ComplexGaussianLikelihood,
    GaussianLikelihood,
)
from spin_dynamics.design.models import PredictiveModel
from spin_dynamics.design.performance import (
    AdaptiveMonteCarloUtility,
    LaplaceInformationGain,
    PolynomialSurrogatePredictor,
    SurrogateValidation,
    TwoStageDesignSession,
    scalar_parameter_encoder,
)
from spin_dynamics.design.posterior import (
    GridPosterior,
    ParticlePosterior,
    posterior_from_state,
)
from spin_dynamics.design.priors import (
    DiscretePrior,
    IndependentPrior,
    LogUniformPrior,
    NormalPrior,
    UniformPrior,
)
from spin_dynamics.design.robustness import (
    ComplexGaussianDiscrepancyLikelihood,
    DesignSensitivityReport,
    ExpectedTargetInformationGain,
    GaussianDiscrepancyLikelihood,
    ModelMixturePredictor,
    SensitivityRecommendation,
    analyze_design_sensitivity,
)

from spin_dynamics.design.reference_ir import (
    IRAcquisitionCost,
    IRAdaptiveSession,
    IRBenchmarkResult,
    IRDesign,
    IRDesignScore,
    IRGridPosterior,
    IRGridPrior,
    IRMeasurement,
    IRRecommendation,
    IRTruth,
    inversion_recovery_signal,
    recommend_ir_design,
    run_ir_reference_trial,
    simulate_ir_observation,
)
from spin_dynamics.design.session import (
    AdaptiveDesignSession,
    CandidateScore,
    DesignObservation,
    DesignRecommendation,
)
from spin_dynamics.design.spaces import CandidateDesignSpace
from spin_dynamics.design.types import (
    ObservationLikelihood,
    ParameterParticles,
    PhysicalCost,
    Prior,
    StopRule,
)
from spin_dynamics.design.utilities import (
    DesignUtility,
    ExpectedInformationGain,
    ExpectedVarianceReduction,
    UtilityEstimate,
)

__all__ = [
    "AcquisitionOutcome",
    "AcquisitionRequest",
    "AdaptiveDesignSession",
    "AdaptiveMonteCarloUtility",
    "AdapterBenchmarkProblem",
    "AdapterBenchmarkResult",
    "BenchmarkPolicySummary",
    "BenchmarkTracePoint",
    "BenchmarkTrial",
    "BatchExecution",
    "CPMGIRAdapter",
    "CPMGIRDesign",
    "CallableConstraint",
    "CallableCost",
    "CandidateDesignSpace",
    "CandidatePredictionTable",
    "CandidateScore",
    "ComplexGaussianLikelihood",
    "ComplexGaussianDiscrepancyLikelihood",
    "ConstantCost",
    "ConstraintResult",
    "CredibleIntervalStopping",
    "DesignConstraint",
    "DesignInstrument",
    "DesignObservation",
    "DesignRecommendation",
    "DesignSensitivityReport",
    "DesignUtility",
    "DiscretePrior",
    "ExpectedInformationGain",
    "ExpectedTargetInformationGain",
    "ExpectedVarianceReduction",
    "ESRDelayDesign",
    "ESRHahnAdapter",
    "ExperimentAdapterCost",
    "ExperimentDesignAdapter",
    "ExperimentPlanConstraint",
    "ExperimentPredictor",
    "GaussianLikelihood",
    "GaussianDiscrepancyLikelihood",
    "GridPosterior",
    "IRAcquisitionCost",
    "IRAdaptiveSession",
    "IRBenchmarkResult",
    "IRDesign",
    "IRDesignScore",
    "IRGridPosterior",
    "IRGridPrior",
    "IRMeasurement",
    "IRRecommendation",
    "IRTruth",
    "IndependentPrior",
    "LogUniformPrior",
    "LaplaceInformationGain",
    "LiveDesignSession",
    "ModelMixturePredictor",
    "NormalPrior",
    "NQRFIDAdapter",
    "NQRFrequencyDesign",
    "NanoMRQdyneAdapter",
    "NanoMRQdyneDesign",
    "ObservationLikelihood",
    "ParameterParticles",
    "ParticlePosterior",
    "PendingBatch",
    "PhysicalCost",
    "PosteriorStandardDeviationStopping",
    "PosteriorSummary",
    "PolynomialSurrogatePredictor",
    "PGSEAdapter",
    "PGSEDesign",
    "PredictiveModel",
    "Prior",
    "QuantityOfInterest",
    "StopRule",
    "SensitivityRecommendation",
    "SurrogateValidation",
    "TwoStageDesignSession",
    "UniformPrior",
    "UtilityEstimate",
    "evaluate_constraints",
    "analyze_design_sensitivity",
    "inversion_recovery_signal",
    "load_design_state",
    "make_adapter_model",
    "make_adapter_session",
    "make_cpmg_ir_benchmark",
    "make_esr_hahn_benchmark",
    "make_nqr_fid_benchmark",
    "make_pgse_benchmark",
    "make_phase2_adapter_benchmarks",
    "posterior_from_state",
    "quantity_values",
    "recommend_ir_design",
    "run_adapter_benchmark",
    "run_ir_reference_trial",
    "save_design_state",
    "save_design_state_atomic",
    "save_benchmark_results",
    "scalar_parameter_encoder",
    "simulate_ir_observation",
    "state_from_json",
    "state_to_json",
    "summarize_quantity",
    "weighted_mean",
    "weighted_quantile",
    "weighted_variance",
]
