"""High-level workflow entry points mirroring canonical MATLAB examples."""

from spin_dynamics.workflows.acquisition import (
    calc_macq_ideal_probe_relax4,
    calc_macq_matched_probe_relax4,
    calc_macq_tuned_probe_relax4,
    calc_macq_untuned_probe_relax4,
)
from spin_dynamics.workflows.cpmg import (
    CPMGResult,
    CPMGTrainResult,
    run_ideal_cpmg,
    run_ideal_cpmg_train,
    run_matched_cpmg,
    run_matched_cpmg_train,
    run_tuned_cpmg,
    run_tuned_cpmg_train,
    run_untuned_cpmg,
    run_untuned_cpmg_train,
)
from spin_dynamics.workflows.cpmg_ir import (
    MatchedCPMGIRTrainResult,
    run_matched_cpmg_ir_train,
)
from spin_dynamics.workflows.diffusion import (
    MatchedDiffusionCPMGResult,
    MatchedDiffusionQSweepResult,
    calc_macq_matched_probe_relax_diffusion,
    run_matched_diffusion_cpmg,
    run_matched_diffusion_q_sweep,
)
from spin_dynamics.workflows.sweeps import (
    CPMGFiniteParameterSweepResult,
    CPMGParameterSweepResult,
    ZMagnetizationSweepResult,
    run_matched_finite_mistuning_sweep,
    run_matched_finite_q_sweep,
    run_matched_mistuning_sweep,
    run_matched_q_sweep,
    run_matched_z_magnetization_q_sweep,
    run_tuned_finite_mistuning_sweep,
    run_tuned_finite_q_sweep,
    run_tuned_mistuning_sweep,
    run_tuned_q_sweep,
    run_untuned_finite_mistuning_sweep,
    run_untuned_finite_q_sweep,
)
from spin_dynamics.workflows.time_varying import (
    IdealTimeVaryingCPMGResult,
    IdealTimeVaryingSweepResult,
    run_ideal_time_varying_amplitude_sweep,
    run_ideal_time_varying_cpmg_final,
    sinusoidal_field_waveform,
)

__all__ = [
    "CPMGResult",
    "CPMGParameterSweepResult",
    "CPMGFiniteParameterSweepResult",
    "CPMGTrainResult",
    "IdealTimeVaryingCPMGResult",
    "IdealTimeVaryingSweepResult",
    "MatchedCPMGIRTrainResult",
    "MatchedDiffusionCPMGResult",
    "MatchedDiffusionQSweepResult",
    "ZMagnetizationSweepResult",
    "calc_macq_ideal_probe_relax4",
    "calc_macq_matched_probe_relax_diffusion",
    "calc_macq_matched_probe_relax4",
    "calc_macq_tuned_probe_relax4",
    "calc_macq_untuned_probe_relax4",
    "run_ideal_cpmg",
    "run_ideal_cpmg_train",
    "run_ideal_time_varying_amplitude_sweep",
    "run_ideal_time_varying_cpmg_final",
    "run_matched_cpmg",
    "run_matched_cpmg_ir_train",
    "run_matched_cpmg_train",
    "run_matched_diffusion_cpmg",
    "run_matched_diffusion_q_sweep",
    "run_matched_finite_mistuning_sweep",
    "run_matched_finite_q_sweep",
    "run_matched_mistuning_sweep",
    "run_matched_q_sweep",
    "run_matched_z_magnetization_q_sweep",
    "run_tuned_cpmg",
    "run_tuned_cpmg_train",
    "run_tuned_finite_mistuning_sweep",
    "run_tuned_finite_q_sweep",
    "run_tuned_mistuning_sweep",
    "run_tuned_q_sweep",
    "run_untuned_cpmg",
    "run_untuned_cpmg_train",
    "run_untuned_finite_mistuning_sweep",
    "run_untuned_finite_q_sweep",
    "sinusoidal_field_waveform",
]
